name: deploy-app
on:
    push:
        branches:
            - "izuna-master"
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Execute Server Command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.AIRI_SSH_HOST }}
                  username: ${{ secrets.AIRI_SSH_USER }}
                  key: ${{ secrets.AIRI_SSH_PRIVATE_KEY }}
                  script: |
                      echo "SSH into the server"
                      docker network disconnect closure-network closure-runtime
                      docker stop closure-runtime
                      docker container rm closure-runtime
                      rm -rf izuna
                      git clone https://github.com/arung-agamani/izuna.git
                      cd izuna
                      git checkout izuna-master
                      docker build . -t izuna-closure:latest
                      cd ..
                      rm -rf izuna
                      docker run -d -p 8001:8000 --name closure-runtime --network=closure-network \
                       --mount source=closure-logs,target=/usr/src/app/log \
                       -e DISCORD_BOT_TOKEN=${{ secrets.CLOSURE_BOT_TOKEN }} -e DATABASE_URL=${{ secrets.CLOSURE_DB_URL }} \
                       -e DISCORD_OAUTH_CLIENT_ID=${{ secrets.CLOSURE_DISCORD_OAUTH_CLIENT_ID}} \
                       -e DISCORD_OAUTH_CLIENT_SECRET=${{ secrets.DISCORD_OAUTH_CLIENT_SECRET}} \
                       -e GOOGLE_CLOSURE_API_KEY=${{ secrets.GOOGLE_CLOSURE_API_KEY}} \
                       -e GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID}} \
                       -e GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET}} \
                       -e KUREYA_LAVALINK_PASSWORD=${{ secrets.KUREYA_LAVALINK_PASSWORD}} \
                       -e NHPROXY_AUTH=${{ secrets.NHPROXY_AUTH }} \
                       -e RUN_BOT=1 -e RUN_WEB=1 \
                       -e AUTH_SECRET=${{ secrets.CLOSURE_AUTH_SECRET }} izuna-closure:latest
