name: deploy-dev
on:
    push:
        branches:
            - dev
    workflow_dispatch:
jobs:
    package:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Check if there is change on certain paths
              uses: dorny/paths-filter@v3
              id: changes
              with:
                  filters: |
                      src:
                        - 'src/**'
                        - 'web/**'
            - name: Docker Login
              if: steps.changes.outputs.src == 'true'
              uses: docker/login-action@v2.1.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_ACCESS_TOKEN }}

            - name: Build and push Docker images
              if: steps.changes.output.src == 'true'
              uses: docker/build-push-action@v3.2.0
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: ghcr.io/arung-agamani/izuna:${{ github.sha }}, ghcr.io/arung-agamani/izuna:latest
    deploy:
        runs-on: ubuntu-latest
        needs: package
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Check if there is change on certain paths
              uses: dorny/paths-filter@v3
              id: changes
              with:
                  filters: |
                      src:
                        - 'src/**'
                        - 'web/**'
            - name: Apply changes to remote server
              if: steps.changes.outputs.src == 'true'
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.KUREYA_SSH_HOST }}
                  username: ${{ secrets.KUREYA_SSH_USER }}
                  key: ${{ secrets.KUREYA_SSH_PRIVATE_KEY }}
                  script: |
                      echo "SSH into the server"
                      export GIT_COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
                      export GIT_COMMIT_HASH="${{ github.sha }}"
                      BUILD_REF="$GIT_COMMIT_HASH - $GIT_COMMIT_MESSAGE" \
                      COMMIT_HASH=${{ steps.changes.output.src == 'true' && github.sha || 'latest' }} \
                      doppler run -- docker compose -f ${{ secrets.COMPOSE_FILE_PATH}} up --force-recreate -d izunabot
                      echo "Deploy done"
