name: deploy-dev
on:
    push:
        branches:
            - dev
    # workflow_dispatch:

jobs:
    package:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Check if there is change on certain paths
              uses: dorny/paths-filter@v2
              id: changes
              with:
                  filters: |
                      src:
                      - 'src/**'
                      - 'web/**'
            - name: Docker Login
              #   if: steps.changes.output.src == 'true'
              uses: docker/login-action@v2.1.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_ACCESS_TOKEN }}

            - name: Build and push Docker images
              #   if: steps.changes.output.src == 'true'
              uses: docker/build-push-action@v3.2.0
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: ghcr.io/arung-agamani/izuna:${{ github.sha }}, ghcr.io/arung-agamani/izuna:latest
    deploy:
        runs-on: ubuntu-latest
        needs: package
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Check if there is change on certain paths
              uses: dorny/paths-filter@v2
              id: changes
              with:
                  filters: |
                      src:
                        - 'src/**'
                        - 'web/**'
            - name: Apply changes to remote server
              #   if: steps.changes.output.src == 'true'
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.KUREYA_SSH_HOST }}
                  username: ${{ secrets.KUREYA_SSH_USER }}
                  key: ${{ secrets.KUREYA_SSH_PRIVATE_KEY }}
                  script: |
                      echo "SSH into the server"
                      export GIT_COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
                      export GIT_COMMIT_HASH="${{ github.sha }}"
                      docker compose -f ${{ secrets.COMPOSE_FILE_PATH}} \
                        -e BUILD_REF: $GIT_COMMIT_HASH - $GIT_COMMIT_MESSAGE \
                        -e COMMIT_HASH: ${{ github.sha }} \
                        -e DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN}} \
                        -e DATABASE_URL: ${{ secrets.DATABASE_URL}} \
                        -e DISCORD_OAUTH_CLIENT_ID: ${{ secrets.DISCORD_OAUTH_CLIENT_ID}} \
                        -e DISCORD_OAUTH_CLIENT_SECRET: ${{ secrets.DISCORD_OAUTH_CLIENT_SECRET}} \
                        -e GOOGLE_CLOSURE_API_KEY: ${{ secrets.GOOGLE_CLOSURE_API_KEY}} \
                        -e GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID}} \
                        -e GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET}} \
                        -e KUREYA_LAVALINK_PASSWORD: ${{ secrets.KUREYA_LAVALINK_PASSWORD}} \
                        -e NHPROXY_AUTH: ${{ secrets.NHPROXY_AUTH}} \
                        -e RUN_BOT: ${{ secrets.RUN_BOT}} \
                        -e RUN_WEB: ${{ secrets.RUN_WEB}} \
                        -e USE_LOKI: ${{ secrets.USE_LOKI}} \
                        -e LOKI_HOST: ${{ secrets.LOKI_HOST}} \
                        -e LOKI_USER: ${{ secrets.LOKI_USER}} \
                        -e LOKI_PASS: ${{ secrets.LOKI_PASS}} \
                        -e LAVALINK_CONFIG_PATH: ${{ secrets.LAVALINK_CONFIG_PATH }} \
                        -e S3_REGION: ${{ secrets.S3_REGION}} \
                        -e S3_BUCKET: ${{ secrets.S3_BUCKET}} \
                        -e S3_CLIENT_ID: ${{ secrets.S3_CLIENT_ID}} \
                        -e S3_CLIENT_SECRET: ${{ secrets.S3_CLIENT_SECRET}} \
                        -e AUTH_SECRET: ${{ secrets.AUTH_SECRET}} \
                        up -d izunabot
                      echo "Deploy done"
